import { 
  IconBook, 
  IconBrain, 
  IconChevronRight, 
  IconChevronLeft, 
  IconLoader2, 
  IconSparkles, 
  IconSettings, 
  IconLogout,
  IconStack2,
  IconCircleCheck,
  IconClock,
  IconDeviceGamepad2,
  IconMaximize,
  IconX,
  IconFileUnknown,
  IconLink,
  IconArrowsSort,
  IconGripVertical,
  IconTrophy,
  IconArrowsShuffle
} from '@tabler/icons-react';

export const Icons = {
  BookOpen: IconBook,
  Brain: IconBrain,
  ChevronRight: IconChevronRight,
  ChevronLeft: IconChevronLeft,
  // Mapping RotateCcw to Loader2 as it is primarily used for loading spinners in the app
  RotateCcw: IconLoader2, 
  Sparkles: IconSparkles,
  Settings: IconSettings,
  LogOut: IconLogout,
  Layers: IconStack2,
  CheckCircle: IconCircleCheck,
  Clock: IconClock,
  Gamepad2: IconDeviceGamepad2,
  Maximize2: IconMaximize,
  X: IconX,
  FileQuestion: IconFileUnknown,
  Link: IconLink,
  ArrowUpDown: IconArrowsSort,
  GripVertical: IconGripVertical,
  Trophy: IconTrophy,
  Shuffle: IconArrowsShuffle
};