import {
  IconBook,
  IconBrain,
  IconChevronRight,
  IconChevronLeft,
  IconLoader2,
  IconSparkles,
  IconSettings,
  IconLogout,
  IconStack2,
  IconCircleCheck,
  IconClock,
  IconDeviceGamepad2,
  IconMaximize,
  IconX,
  IconFileUnknown,
  IconLink,
  IconArrowsSort,
  IconGripVertical,
  IconTrophy,
  IconArrowsShuffle,
  IconGridDots,
  IconCheck,
  IconBulb,
  IconPlayerSkipForward,
  IconEraser,
  IconMenu2,
  IconVolume,
  IconVolumeOff,
  IconListCheck,
  IconHelpCircle,
  IconInfoCircle,
  IconKeyboard,
  IconAdjustments,
  IconPuzzle,
  IconMusic,
  IconHome,
  IconBrandGithub,
  IconActivity,
  IconSun,
  IconMoon,
} from '@tabler/icons-react'

export const Icons = {
  BookOpen: IconBook,
  Brain: IconBrain,
  ChevronRight: IconChevronRight,
  ChevronLeft: IconChevronLeft,
  RotateCcw: IconLoader2,
  Sparkles: IconSparkles,
  Settings: IconSettings,
  LogOut: IconLogout,
  Layers: IconStack2,
  CheckCircle: IconCircleCheck,
  Clock: IconClock,
  Gamepad2: IconDeviceGamepad2,
  Maximize2: IconMaximize,
  X: IconX,
  FileQuestion: IconFileUnknown,
  Link: IconLink,
  ArrowUpDown: IconArrowsSort,
  GripVertical: IconGripVertical,
  Trophy: IconTrophy,
  Shuffle: IconArrowsShuffle,
  GridDots: IconGridDots,
  Check: IconCheck,
  Lightbulb: IconBulb,
  SkipForward: IconPlayerSkipForward,
  Eraser: IconEraser,
  Menu: IconMenu2,
  Volume: IconVolume,
  VolumeOff: IconVolumeOff,
  ListCheck: IconListCheck,
  Help: IconHelpCircle,
  Info: IconInfoCircle,
  Keyboard: IconKeyboard,
  Adjustments: IconAdjustments,
  Puzzle: IconPuzzle,
  Music: IconMusic,
  Home: IconHome,
  GitHub: IconBrandGithub,
  Activity: IconActivity,
  Sun: IconSun,
  Moon: IconMoon,
}
